// Returns a markdown string that displays a license badge based on the license that is passed in
// If there is no license, return an empty string
function renderLicenseBadge(license) {
  if (!license) {
    return '';
  }

  const licenseType = license.toLowerCase().replace(/ /g, '-');
  return `![License](https://img.shields.io/badge/license-${licenseType}-blue.svg)`;
}


// Returns a markdown link to the official license page based on the license type
function renderLicenseLink(license) {
  if (!license) {
    return '';
  }

  const licenseType = license.toLowerCase().replace(/ /g, '-');
  return `[${license}](https://opensource.org/licenses/${licenseType})`;
}


// Returns a markdown section with the license information, including a link to the license page generated by renderLicenseLink
function renderLicenseSection(license) {
  if (!license) {
    return '';
  }

  return `
## License

This project is licensed under the ${renderLicenseLink(license)} license.
`;
}

// Generates markdown for the README file using data provided.
// Includes the license badge, project title, project description, and license section
function generateMarkdown(data) {
  const licenseBadge = renderLicenseBadge(data.license);
  const licenseSection = renderLicenseSection(data.license);

  return `# ${data.title}

${licenseBadge}

${data.description}

${licenseSection}
`;
}

module.exports = {
  renderLicenseBadge,
  renderLicenseLink,
  renderLicenseSection,
  generateMarkdown,
};
